Citizen.CreateThread(function()
    local pxBlip = AddBlipForCoord(Config.Blip.coords)
    SetBlipSprite(pxBlip, Config.Blip.id)
    SetBlipDisplay(pxBlip, 4)
    SetBlipScale(pxBlip, Config.Blip.scale)
    SetBlipColour(pxBlip, Config.Blip.color)
    SetBlipAsShortRange(pxBlip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString(Config.Blip.title)
    EndTextCommandSetBlipName(pxBlip)
end)